module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
modules:
  Foundation:
    filename: src/Foundation.hs
  Handler.Home:
    filename: src/Handler/Home.hs
  Handler.Preview:
    filename: src/Handler/Preview.hs
  Handler.Download:
    filename: src/Handler/Download.hs
  Dispatch:
    filename: src/Dispatch.hs
  Main(src/Main.hs):
    filename: src/Main.hs
version: 1
extra-packages: ''
ghc-args: []
